/*
 * design-catalog.js
 * ShowMeCSS / Micss PTZ Web Components
 * Vanilla JavaScript + Custom Elements + Shadow DOM only.
 * No framework, build tool, or external CSS is required.
 */
(() => {
  'use strict';

  const PTZ_DEFAULTS = {
    themeName: 'ShowMeCSS Default Blue', accentColor: '#3381FF', cardRadius: 24,
    sliderHeight: 25, toggleWidth: 54, toggleHeight: 30, toggleKnobRadius: 50,
    toggleKnobWidth: 22, bgLight: '#F7F7F7', bgDark: '#121212'
  };

  const PTZ_PRESETS = {
    default: { ...PTZ_DEFAULTS, sliderHeight: 20 },
    sharpPurple: { themeName: 'Sharp Purple PTZ', accentColor: '#8B5CF6', cardRadius: 0, sliderHeight: 14, toggleWidth: 50, toggleHeight: 26, toggleKnobRadius: 0, toggleKnobWidth: 18, bgLight: '#FFFFFF', bgDark: '#1C1C1E' },
    chunkyRose: { themeName: 'Chunky Rose PTZ', accentColor: '#EC4899', cardRadius: 32, sliderHeight: 24, toggleWidth: 64, toggleHeight: 36, toggleKnobRadius: 50, toggleKnobWidth: 28, bgLight: '#FFF1F2', bgDark: '#1A0B0E' },
    minimalGray: { themeName: 'Minimal Monochrome PTZ', accentColor: '#64748B', cardRadius: 12, sliderHeight: 16, toggleWidth: 46, toggleHeight: 24, toggleKnobRadius: 50, toggleKnobWidth: 16, bgLight: '#F3F4F6', bgDark: '#0F0F10' }
  };

  const css = String.raw`
    :host { box-sizing:border-box; color:var(--text-main); font-family:'Plus Jakarta Sans','Noto Sans JP',sans-serif; }
    *,*::before,*::after{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
    button,input,textarea{font:inherit}
    .card{background:var(--glass-bg);border-radius:var(--ptz-card-radius);padding:var(--card-padding);margin-bottom:20px;box-shadow:none!important;border:none!important;transition:background-color var(--transition-smooth),border-radius var(--transition-smooth)}
    h2{font-size:18px;margin:0 0 12px;font-weight:700;letter-spacing:-.3px} p{font-size:13.5px;line-height:1.5;margin:0 0 16px;color:var(--text-sub)}
    .list{display:flex;flex-direction:column;gap:6px;margin-bottom:16px}.list-item,.toggle-row{display:flex;align-items:center;justify-content:space-between;padding:10px 4px;border-bottom:none!important}.list-title{font-weight:600;font-size:14px}.list-desc{font-size:12px;color:var(--text-sub);margin-top:2px}
    .slider-wrap{margin:16px 0}.slider-label{display:flex;justify-content:space-between;font-size:13px;font-weight:600;margin-bottom:8px}.thick-slider{position:relative;width:100%;height:var(--ptz-slider-height);background:var(--bg-secondary);border-radius:calc(var(--ptz-slider-height)/2);overflow:hidden;cursor:pointer;display:flex;align-items:center}.slider-fill{position:absolute;top:0;left:0;height:100%;width:50%;background:var(--accent-primary);border-radius:calc(var(--ptz-slider-height)/2);display:flex;align-items:center;justify-content:flex-end;padding-right:3px;transition:background-color var(--transition-smooth),width .05s ease-out}.slider-knob{width:calc(var(--ptz-slider-height) - 6px);height:calc(var(--ptz-slider-height) - 6px);background:#FFF;border-radius:50%;box-shadow:0 1px 3px rgba(0,0,0,.25);flex-shrink:0}.slider-input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:pointer;margin:0;z-index:2}
    .switch{position:relative;display:inline-block;width:var(--ptz-toggle-width);height:var(--ptz-toggle-height);flex:0 0 auto}.switch input{opacity:0;width:0;height:0}.switch-track{position:absolute;inset:0;cursor:pointer;background:var(--bg-secondary);transition:var(--transition-smooth);border-radius:calc(var(--ptz-toggle-height)/2)}.switch-track::before{position:absolute;content:'';height:var(--ptz-toggle-knob-width);width:var(--ptz-toggle-knob-width);left:4px;bottom:calc((var(--ptz-toggle-height) - var(--ptz-toggle-knob-width))/2);background:#FFF;transition:var(--transition-smooth);border-radius:var(--ptz-toggle-knob-radius);box-shadow:0 1px 3px rgba(0,0,0,.15)}input:checked+.switch-track{background:var(--accent-primary)}input:checked+.switch-track::before{transform:translateX(calc(var(--ptz-toggle-width) - var(--ptz-toggle-knob-width) - 8px))}
    .btn{border:0;outline:0;padding:12px 24px;border-radius:14px;font-weight:600;font-size:14px;color:#FFF;cursor:pointer;background:var(--accent-primary);transition:opacity .2s,background-color var(--transition-smooth);display:inline-flex;align-items:center;gap:8px;justify-content:center}.btn:active{opacity:.85}.btn.secondary{background:var(--bg-secondary);color:var(--text-main)}
    .input-wrap{margin-bottom:14px}.input{width:100%;padding:12px 16px;border-radius:12px;border:0;background:var(--bg-secondary);color:var(--text-main);font-size:14px;box-sizing:border-box;transition:background var(--transition-smooth)}.input:focus{outline:2px solid var(--accent-primary)}
    .nav{position:fixed;bottom:0;left:0;width:100%;height:72px;background:var(--nav-bg);border-top:1px solid var(--bg-secondary);z-index:500;display:flex;justify-content:space-around;align-items:center;padding-bottom:env(safe-area-inset-bottom);transition:background-color var(--transition-smooth),border-color var(--transition-smooth)}.nav-item{flex:1;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer;color:var(--text-sub);transition:color .25s var(--m3-easing);position:relative;gap:4px}.nav-item.active{color:var(--nav-icon-active)}.nav-icon{font-size:24px;line-height:1}.nav-label{font-size:10px;font-weight:600}
    .view{display:none}.view.active{display:block;animation:viewIn .3s var(--m3-easing)}@keyframes viewIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
    .dropzone{border:2px dashed var(--text-sub);border-radius:var(--ptz-card-radius);padding:24px;text-align:center;cursor:pointer;background:rgba(0,0,0,.02);transition:background .2s,border-color .2s;margin-bottom:16px}.dropzone:hover,.dropzone.dragover{background:rgba(51,129,255,.1);border-color:var(--accent-primary)}
    .json{width:100%;height:220px;font-family:'Fira Code',monospace;font-size:12.5px;padding:16px;background:var(--bg-secondary);color:var(--text-main);border:0;border-radius:var(--ptz-card-radius);resize:vertical;outline:0;line-height:1.4}.json:focus{box-shadow:0 0 0 2px var(--accent-primary)}.error{color:#FF3B30;font-size:12px;margin-top:6px;display:none;font-weight:600}.error.visible{display:block}
    .preset-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:10px;margin-top:10px}.preset{background:var(--bg-secondary);color:var(--text-main);border:0;padding:10px;border-radius:12px;font-size:12px;font-weight:600;cursor:pointer;text-align:center}.preset:active{opacity:.8}
    .code{background:var(--bg-secondary);border-radius:12px;padding:14px;font-family:'Fira Code',monospace;font-size:12px;color:var(--text-main);overflow-x:auto;white-space:pre-wrap;margin-bottom:12px;line-height:1.4}
    .toast{position:fixed;bottom:84px;left:50%;transform:translateX(-50%) translateY(20px);background:var(--text-main);color:var(--glass-bg);padding:10px 20px;border-radius:12px;font-size:13px;font-weight:600;opacity:0;visibility:hidden;transition:all .3s var(--m3-easing);z-index:2000}.toast.active{opacity:1;visibility:visible;transform:translateX(-50%) translateY(0)}
    .overlay{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:1000;display:flex;align-items:center;justify-content:center;opacity:0;visibility:hidden;transition:all .3s var(--m3-easing)}.overlay.active{opacity:1;visibility:visible}.dialog{background:var(--glass-bg);border-radius:var(--ptz-card-radius);padding:24px;max-width:380px;width:90%;text-align:center;transform:scale(.9) translateY(20px);transition:all .4s var(--m3-easing)}.overlay.active .dialog{transform:scale(1) translateY(0)}
    .badge{background:var(--accent-primary);color:#FFF;padding:3px 10px;border-radius:10px;font-size:11px;font-weight:700;display:inline-block}.colors{display:flex;gap:10px;margin:12px 0}.swatch{width:36px;height:36px;border-radius:50%;cursor:pointer;border:2px solid transparent;transition:opacity .2s,border-color .2s}.swatch.active,.swatch:active{border-color:var(--text-main)}
    .header{height:64px;padding:0 24px;display:flex;align-items:center;justify-content:center;background:var(--bg-base);position:relative;z-index:10}.logo{font-weight:700;font-size:18px;letter-spacing:-.5px}.theme-btn{position:absolute;right:24px;width:40px;height:40px;border-radius:50%;border:0;background:var(--bg-secondary);color:var(--text-main);cursor:pointer}.scroll{flex-grow:1;overflow-y:auto;padding:12px 20px 100px;max-width:720px;width:100%;margin:0 auto;-webkit-overflow-scrolling:touch;overscroll-behavior-y:none}.overscroll{transform-origin:center top}.overscroll.spring-back{transition:transform .5s cubic-bezier(.175,.885,.32,1.275)}
    .icon{font-size:24px;line-height:1;display:inline-block}.muted{color:var(--text-sub)}
    ::slotted(h2){font-size:18px;margin:0 0 12px;font-weight:700;letter-spacing:-.3px}::slotted(p){font-size:13.5px;line-height:1.5;margin:0 0 16px;color:var(--text-sub)}::slotted([slot="logo"]){font-weight:700;font-size:18px;letter-spacing:-.5px}::slotted([slot="title"]){font-weight:600;font-size:14px}::slotted([slot="description"]){font-size:12px;color:var(--text-sub);margin-top:2px}
  `;

  const style = () => { const s = document.createElement('style'); s.textContent = css; return s; };
  const shadow = (el, body) => { const root = el.attachShadow({mode:'open'}); root.append(body, style()); return root; };
  const slot = (name = '') => `<slot${name ? ` name="${name}"` : ''}></slot>`;
  const emit = (el, name, detail = {}) => el.dispatchEvent(new CustomEvent(name, { bubbles:true, composed:true, detail }));
  const attr = (el, name, fallback='') => el.getAttribute(name) ?? fallback;

  class DCBase extends HTMLElement { static get observedAttributes(){ return ['theme','accent','card-radius','slider-height','toggle-width','toggle-height','bg-light','bg-dark']; } connectedCallback(){ if (!this.shadowRoot) this.render(); this.sync(); } attributeChangedCallback(){ if(this.isConnected) this.sync(); } render(){ shadow(this, document.createElement('div')); } sync(){ const r=this.style; const map={accent:'--accent-primary','card-radius':'--ptz-card-radius','slider-height':'--ptz-slider-height','toggle-width':'--ptz-toggle-width','toggle-height':'--ptz-toggle-height'}; Object.entries(map).forEach(([a,v])=>{if(this.hasAttribute(a))r.setProperty(v, attr(this,a)+(a==='accent'?'':'px'))}); } }

  class DCTheme extends DCBase { render(){ const root=shadow(this, document.createElement('button')); root.firstElementChild.className='theme-btn'; root.firstElementChild.title=attr(this,'label','テーマ切り替え'); root.firstElementChild.innerHTML='<span class="icon" aria-hidden="true">☼</span>'; root.firstElementChild.addEventListener('click',()=>{ const dark=document.documentElement.classList.toggle('dark-mode'); root.firstElementChild.querySelector('.icon').textContent=dark?'☾':'☼'; this.setAttribute('mode',dark?'dark':'light'); emit(this,'dc-theme-change',{dark}); }); } }
  class DCHeader extends DCBase { render(){ const root=shadow(this, document.createElement('header')); root.firstElementChild.className='header'; root.firstElementChild.innerHTML=`<div class="logo">${slot('logo')}</div><dc-theme-toggle></dc-theme-toggle>`; } }
  class DCCard extends DCBase { render(){ const root=shadow(this,document.createElement('div')); root.firstElementChild.className='card'; root.firstElementChild.innerHTML=slot(); } }
  class DCList extends DCBase { render(){ const root=shadow(this,document.createElement('div')); root.firstElementChild.className='list'; root.firstElementChild.innerHTML=slot(); } }
  class DCListItem extends DCBase { render(){ const root=shadow(this,document.createElement('div')); root.firstElementChild.className='list-item'; root.firstElementChild.innerHTML=`<div><div class="list-title">${slot('title')}</div><div class="list-desc">${slot('description')}</div></div><slot name="action"></slot>`; } }
  class DCButton extends DCBase { static get observedAttributes(){return ['variant','type','disabled','label'];} render(){ const root=shadow(this,document.createElement('button')); const b=root.firstElementChild; b.className='btn'; b.type=attr(this,'type','button'); b.innerHTML=slot(); b.addEventListener('click',e=>{if(!this.hasAttribute('disabled'))emit(this,'dc-press',{originalEvent:e});}); } sync(){super.sync();const b=this.shadowRoot?.firstElementChild;if(b){b.classList.toggle('secondary',attr(this,'variant')==='secondary');b.disabled=this.hasAttribute('disabled');}} }
  class DCToggle extends DCBase { static get observedAttributes(){return ['checked','disabled','name'];} render(){const root=shadow(this,document.createElement('label')); root.firstElementChild.className='switch'; root.firstElementChild.innerHTML='<input type="checkbox"><span class="switch-track"></span>'; const input=root.querySelector('input'); input.addEventListener('change',()=>{this.toggleAttribute('checked',input.checked);emit(this,'dc-change',{checked:input.checked});}); } sync(){super.sync();const i=this.shadowRoot?.querySelector('input');if(i){i.checked=this.hasAttribute('checked');i.disabled=this.hasAttribute('disabled');}} }
  class DCSlider extends DCBase { static get observedAttributes(){return ['min','max','value','step','unit','label'];} render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='slider-wrap';root.firstElementChild.innerHTML=`<div class="slider-label"><span>${attr(this,'label','')}</span><span class="value"></span></div><div class="thick-slider"><div class="slider-fill"><div class="slider-knob"></div></div><input class="slider-input" type="range"></div>`;const i=root.querySelector('input');i.addEventListener('input',()=>{this.setAttribute('value',i.value);this.update();emit(this,'dc-input',{value:Number(i.value)});});} sync(){super.sync();const i=this.shadowRoot?.querySelector('input');if(i){['min','max','step','value'].forEach(a=>{if(this.hasAttribute(a))i[a]=this.getAttribute(a)});this.update();}} update(){const i=this.shadowRoot?.querySelector('input');if(!i)return;const min=Number(i.min||0),max=Number(i.max||100),v=Number(i.value||0),p=((v-min)/(max-min))*100;this.shadowRoot.querySelector('.slider-fill').style.width=`${Math.max(0,Math.min(100,p))}%`;this.shadowRoot.querySelector('.value').textContent=`${i.value}${attr(this,'unit','')}`;} }
  class DCInput extends DCBase { static get observedAttributes(){return ['type','value','placeholder','name','disabled'];} render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='input-wrap';root.firstElementChild.innerHTML='<input class="input">';const i=root.querySelector('input');i.addEventListener('input',()=>emit(this,'dc-input',{value:i.value}));} sync(){super.sync();const i=this.shadowRoot?.querySelector('input');if(i){['type','value','placeholder','name'].forEach(a=>{if(this.hasAttribute(a))i[a]=this.getAttribute(a)});i.disabled=this.hasAttribute('disabled');}} }
  class DCBadge extends DCBase { render(){const root=shadow(this,document.createElement('span'));root.firstElementChild.className='badge';root.firstElementChild.innerHTML=slot();} }
  class DCColorSwatch extends DCBase { static get observedAttributes(){return ['color','active'];} render(){const root=shadow(this,document.createElement('button'));const b=root.firstElementChild;b.className='swatch';b.type='button';b.addEventListener('click',()=>{this.setAttribute('active','');emit(this,'dc-color-change',{color:this.color});});} sync(){super.sync();const b=this.shadowRoot?.firstElementChild;if(b){b.style.background=attr(this,'color','#3381FF');b.classList.toggle('active',this.hasAttribute('active'));}} get color(){return attr(this,'color','#3381FF');} }
  class DCColorGrid extends DCBase { render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='colors';root.firstElementChild.innerHTML=slot();root.firstElementChild.addEventListener('dc-color-change',e=>{this.querySelectorAll('dc-color-swatch').forEach(x=>x.removeAttribute('active'));e.target.setAttribute('active','');emit(this,'dc-color-change',e.detail);});} }
  class DCNavItem extends DCBase { static get observedAttributes(){return ['active','view','icon','label'];} render(){const root=shadow(this,document.createElement('div'));const n=root.firstElementChild;n.className='nav-item';n.innerHTML=`<span class="nav-icon">${attr(this,'icon','style')}</span><span class="nav-label">${attr(this,'label','')}</span>`;n.addEventListener('click',()=>emit(this,'dc-navigate',{view:attr(this,'view')}));} sync(){super.sync();this.shadowRoot?.firstElementChild.classList.toggle('active',this.hasAttribute('active'));} }
  class DCNav extends DCBase { render(){const root=shadow(this,document.createElement('nav'));root.firstElementChild.className='nav';root.firstElementChild.innerHTML=slot();root.firstElementChild.addEventListener('dc-navigate',e=>{this.querySelectorAll('dc-nav-item').forEach(x=>x.toggleAttribute('active',x.getAttribute('view')===e.detail.view));emit(this,'dc-navigate',e.detail);});} }
  class DCView extends DCBase { static get observedAttributes(){return ['active'];} render(){const root=shadow(this,document.createElement('section'));root.firstElementChild.className='view';root.firstElementChild.innerHTML=slot();} sync(){super.sync();this.shadowRoot?.firstElementChild.classList.toggle('active',this.hasAttribute('active'));} }
  class DCCode extends DCBase { render(){const root=shadow(this,document.createElement('pre'));root.firstElementChild.className='code';root.firstElementChild.innerHTML=slot();} }
  class DCToast extends DCBase { static get observedAttributes(){return ['open','message'];} render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='toast';root.firstElementChild.innerHTML=slot();} sync(){super.sync();const t=this.shadowRoot?.firstElementChild;if(t){t.classList.toggle('active',this.hasAttribute('open'));if(this.hasAttribute('message'))t.textContent=this.getAttribute('message');}} show(message,duration=2200){if(message)this.setAttribute('message',message);this.setAttribute('open','');clearTimeout(this.timer);this.timer=setTimeout(()=>this.removeAttribute('open'),duration);} }
  class DCDialog extends DCBase { static get observedAttributes(){return ['open'];} render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='overlay';root.firstElementChild.innerHTML='<div class="dialog"><slot></slot></div>';root.firstElementChild.addEventListener('click',e=>{if(e.target===root.firstElementChild)this.removeAttribute('open');});} sync(){super.sync();this.shadowRoot?.firstElementChild.classList.toggle('active',this.hasAttribute('open'));} open(){this.setAttribute('open','')} close(){this.removeAttribute('open')} }
  class DCDropzone extends DCBase { render(){const root=shadow(this,document.createElement('div'));const d=root.firstElementChild;d.className='dropzone';d.innerHTML=`<slot></slot><input type="file" accept=".json,application/json" hidden>`;const i=d.querySelector('input');d.addEventListener('click',()=>i.click());d.addEventListener('dragover',e=>{e.preventDefault();d.classList.add('dragover')});d.addEventListener('dragleave',()=>d.classList.remove('dragover'));d.addEventListener('drop',e=>{e.preventDefault();d.classList.remove('dragover');this.read(e.dataTransfer.files[0])});i.addEventListener('change',()=>this.read(i.files[0]));} read(file){if(!file)return;const r=new FileReader();r.onload=()=>emit(this,'dc-file',{file,text:r.result});r.readAsText(file);} }
  class DCJsonEditor extends DCBase { static get observedAttributes(){return ['value'];} render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.innerHTML='<textarea class="json"></textarea><div class="error" role="alert"></div>';const t=root.querySelector('textarea');t.addEventListener('input',()=>this.validate());} sync(){super.sync();const t=this.shadowRoot?.querySelector('textarea');if(t&&this.hasAttribute('value')&&t.value!==this.getAttribute('value'))t.value=this.getAttribute('value');} validate(){const t=this.shadowRoot.querySelector('textarea'),e=this.shadowRoot.querySelector('.error');try{const value=JSON.parse(t.value);e.classList.remove('visible');emit(this,'dc-json',{value,text:t.value});return value;}catch(err){e.textContent=`JSON構文エラー: ${err.message}`;e.classList.add('visible');emit(this,'dc-json-error',{error:err});return null;}} get value(){return this.shadowRoot?.querySelector('textarea')?.value||'';} set value(v){if(this.shadowRoot)this.shadowRoot.querySelector('textarea').value=typeof v==='string'?v:JSON.stringify(v,null,2);} }
  class DCPresetGrid extends DCBase { render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.className='preset-grid';root.firstElementChild.innerHTML=slot();root.firstElementChild.addEventListener('click',e=>{const b=e.target.closest('button');if(b)emit(this,'dc-preset',{preset:b.dataset.preset||b.textContent});});} }
  class DCPTZProvider extends DCBase { render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.innerHTML=slot();this.ptz={...PTZ_DEFAULTS};} connectedCallback(){super.connectedCallback();this.apply(this.ptz);} apply(next){this.ptz={...this.ptz,...next};const p=this.ptz;const r=this.style;r.setProperty('--accent-primary',p.accentColor);r.setProperty('--ptz-card-radius',`${p.cardRadius}px`);r.setProperty('--ptz-slider-height',`${p.sliderHeight}px`);r.setProperty('--ptz-toggle-width',`${p.toggleWidth}px`);r.setProperty('--ptz-toggle-height',`${p.toggleHeight}px`);r.setProperty('--ptz-toggle-knob-radius',typeof p.toggleKnobRadius==='number'?`${p.toggleKnobRadius}%`:p.toggleKnobRadius);r.setProperty('--ptz-toggle-knob-width',`${p.toggleKnobWidth}px`);r.setProperty('--bg-base',p.bgLight);emit(this,'dc-ptz-change',{ptz:{...this.ptz}});} preset(name){if(PTZ_PRESETS[name])this.apply(PTZ_PRESETS[name]);} export(){return {...this.ptz};} }
  class DCScroll extends DCBase { render(){const root=shadow(this,document.createElement('div'));root.firstElementChild.innerHTML=`<div class="scroll"><div class="overscroll"><slot></slot></div></div>`;const s=root.querySelector('.scroll'),o=root.querySelector('.overscroll');let start=0,pull=0,pulling=false,wheel=0,timer; s.addEventListener('touchstart',e=>{if(e.touches.length===1){start=e.touches[0].clientY;o.classList.remove('spring-back')}});s.addEventListener('touchmove',e=>{if(e.touches.length!==1)return;const d=e.touches[0].clientY-start,top=s.scrollTop<=0,bottom=Math.abs(s.scrollHeight-s.clientHeight-s.scrollTop)<2;if((top&&d>0)||(bottom&&d<0)){pull=d*.38;o.style.transform=`translateY(${pull}px) scaleY(${1+Math.abs(pull)*.0003})`;pulling=true}});s.addEventListener('touchend',()=>{if(pulling){o.classList.add('spring-back');o.style.transform='translateY(0) scaleY(1)';pulling=false}});s.addEventListener('wheel',e=>{const top=s.scrollTop<=0,bottom=Math.abs(s.scrollHeight-s.clientHeight-s.scrollTop)<2;if((top&&e.deltaY<0)||(bottom&&e.deltaY>0)){wheel=Math.max(-60,Math.min(60,wheel-e.deltaY*.25));o.classList.remove('spring-back');o.style.transform=`translateY(${wheel}px)`;clearTimeout(timer);timer=setTimeout(()=>{o.classList.add('spring-back');o.style.transform='translateY(0)';wheel=0},120)}});} }

  const defs = {
    'dc-header':DCHeader,'dc-theme-toggle':DCTheme,'dc-card':DCCard,'dc-list':DCList,'dc-list-item':DCListItem,
    'dc-button':DCButton,'dc-toggle':DCToggle,'dc-slider':DCSlider,'dc-input':DCInput,'dc-badge':DCBadge,
    'dc-color-swatch':DCColorSwatch,'dc-color-grid':DCColorGrid,'dc-nav':DCNav,'dc-nav-item':DCNavItem,
    'dc-view':DCView,'dc-code':DCCode,'dc-toast':DCToast,'dc-dialog':DCDialog,'dc-dropzone':DCDropzone,
    'dc-json-editor':DCJsonEditor,'dc-preset-grid':DCPresetGrid,'dc-ptz-provider':DCPTZProvider,'dc-scroll':DCScroll
  };
  const globalStyle = document.createElement('style');
  globalStyle.dataset.designCatalogDefaults = 'true';
  globalStyle.textContent = `:root{--accent-primary:#3381FF;--accent-active:#1A5FCC;--ptz-card-radius:24px;--ptz-slider-height:25px;--ptz-toggle-width:54px;--ptz-toggle-height:30px;--ptz-toggle-knob-radius:50%;--ptz-toggle-knob-width:22px;--bg-base:#F7F7F7;--glass-bg:#FFF;--text-main:#000;--text-sub:#666;--bg-secondary:#EEE;--nav-bg:#FFF;--nav-icon-active:#000;--m3-easing:cubic-bezier(.32,.72,0,1);--transition-smooth:.35s var(--m3-easing);--card-padding:24px}`;
  document.head.appendChild(globalStyle);
  const hostStyle = document.createElement('style');
  hostStyle.dataset.designCatalogHosts = 'true';
  hostStyle.textContent = 'dc-header,dc-scroll,dc-card,dc-list,dc-list-item,dc-slider,dc-input,dc-color-grid,dc-nav,dc-toast,dc-dialog,dc-dropzone,dc-json-editor,dc-preset-grid,dc-ptz-provider,dc-view,dc-code{display:block}dc-button,dc-toggle,dc-badge,dc-color-swatch,dc-theme-toggle{display:inline-block}dc-nav-item{display:block;flex:1 1 0;height:100%}';
  document.head.appendChild(hostStyle);
  Object.entries(defs).forEach(([name, C])=>{if(!customElements.get(name))customElements.define(name,C);});

  // Public, framework-free helpers for pages that prefer imperative integration.
  window.DesignCatalog = Object.freeze({ PTZ_DEFAULTS:{...PTZ_DEFAULTS}, PTZ_PRESETS:{...PTZ_PRESETS}, applyPtz(ptz, target=document.documentElement){Object.entries(ptz||{}).forEach(([k,v])=>{const map={accentColor:'--accent-primary',cardRadius:'--ptz-card-radius',sliderHeight:'--ptz-slider-height',toggleWidth:'--ptz-toggle-width',toggleHeight:'--ptz-toggle-height',toggleKnobWidth:'--ptz-toggle-knob-width'};if(map[k])target.style.setProperty(map[k],k==='accentColor'?v:`${v}px`);});}, adjustColorBrightness(hex,percent){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)*(100+percent)/100)),g=Math.max(0,Math.min(255,((n>>8)&255)*(100+percent)/100)),b=Math.max(0,Math.min(255,(n&255)*(100+percent)/100));return '#'+[r,g,b].map(x=>Math.round(x).toString(16).padStart(2,'0')).join('');}});
})();
